workflows:
  ios-workflow:
    name: iOS Unsigned (Sideloadly)
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: default

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Pod install
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build iOS app (no codesign)
        script: |
          flutter build ios --release --no-codesign || true

      - name: Package unsigned ipa
        script: |
          echo "Searching Runner.app..."

          find build -name "Runner.app"

          APP=$(find build -name "Runner.app" | head -n 1)

          echo "FOUND: $APP"

          if [ -z "$APP" ]; then
            echo "Runner.app not found"
            exit 1
          fi

          rm -rf Payload
          mkdir Payload

          cp -R "$APP" Payload/Runner.app

          zip -r Runner-unsigned.ipa Payload

    artifacts:
      - Runner-unsigned.ipa
      - build/**/Runner.app

  android-workflow:
    name: Android Build

    environment:
      flutter: stable

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk